### PR TITLE
fix(url_for & full_url_for): ignore data url

### LINKED ISSUE #122: url_for helper doesn't work for mailto link
https://github.com/hexojs/hexo-util/blob/master/lib/url_for.js#L28-L31

it will return origin path when met external link like http://example.com, but will not return origin path for mailto: someone@example.com. and lead to an issue when relative_link was set.

url_for('/category') => /relative_link/category <= OK!
url_for('http://example.com') => http://example.com <= OK!
url_for('mailto:someone@example.com') => /relative_link/mailto:someone@example.com <= Ops!

### PR DESCRIPTION
**Pull request by curbengh**
Fixes #122 

BREAKING CHANGE: drop support for pathname with semicolon

cc @lookis

### CODE REVIEW

File: lib/full_url_for.js [hunk 1]
```diff
@@ -10,8 +10,8 @@ function fullUrlForHelper(path = '/') {
   const sitehost = parse(config.url).hostname || config.url;
   const data = new URL(path, `http://${sitehost}`);
 
-  // Exit if this is an external link
-  if (data.origin !== 'null' && data.hostname !== sitehost) return path;
+  // Exit if input is a data url or external link
+  if (data.origin === 'null' || data.hostname !== sitehost) return path;
```
Comment (SukkaW) [inline lib/full_url_for.js]:
```suggestion
  if (data.hostname !== sitehost || data.origin === 'null') return path;
```

IMHO, external link should be more common than `mailto:`, `javascript:` url. If we change the order, we might increase performance by just a little bit.

Comment (curbengh) [reply lib/full_url_for.js]: updated
