### PR TITLE
fix: handle url with hash, query, auth and port

### LINKED ISSUE #83: encodeURL() will lose hash in URL
```javascript
const { encodeURL } = require("hexo-util");
console.log(encodeURL('https://example.com/blog/#test'));
// "https://example.test/blog/"
```

```javascript
const { encodeURL } = require("hexo-util");
encodeURL('https://example.com/#test');
// "https://example.com/"
```

https://github.com/hexojs/hexo-util/blob/a3abc361caec3f1c09108141c23f2d813d0d387d/lib/encode_url.js#L10

`pathname` doesn't include `hash`. `parse(str).href` should be used in this case.

@curbengh

### PR DESCRIPTION
**Pull request by curbengh**
Fixes #83

### CODE REVIEW

**Comment by curbengh** [comment]
The [URL API](https://nodejs.org/api/url.html#url_legacy_url_api) mentions `path` includes pathname and query, but
```format({ path: encodeURI(decodeURI(parse(str).path)) })```
doesn't output path nor query, thus `pathname` is used instead.

File: lib/encode_url.js [hunk 1]
```diff
@@ -4,11 +4,21 @@ const { parse, format } = require('url');
 
 function encodeURL(str) {
   if (parse(str).protocol) {
-    return format({
+    const obj = Object.assign({}, {
       protocol: parse(str).protocol,
       hostname: parse(str).hostname,
```
Comment (SukkaW) [inline lib/encode_url.js]: Should it use `host` instead of `hostname`? `host` includes port while `hostname` doesn't.

And `auth` (`user:pass`) might be needed in output result (without encoded) as well.

Comment (curbengh) [reply lib/encode_url.js]: Fixed
